In [1]:
import torch

In [2]:
tensor_A = torch.rand(size=(7,7))
tensor_A

tensor([[0.7762, 0.9295, 0.3757, 0.6092, 0.2020, 0.1275, 0.7175],
        [0.5767, 0.1997, 0.8474, 0.9999, 0.8490, 0.2969, 0.8550],
        [0.4672, 0.6071, 0.6846, 0.7418, 0.0017, 0.4216, 0.2892],
        [0.6673, 0.4826, 0.8858, 0.1422, 0.9531, 0.6725, 0.4164],
        [0.2863, 0.2168, 0.3177, 0.7802, 0.2937, 0.4690, 0.7465],
        [0.6619, 0.6927, 0.6693, 0.8488, 0.9949, 0.2252, 0.5229],
        [0.5391, 0.7811, 0.8657, 0.2126, 0.6610, 0.0434, 0.0572]])

In [3]:
tensor_B = torch.rand(size=(1,7))
tensor_B

tensor([[0.1793, 0.2662, 0.9235, 0.4929, 0.7566, 0.4850, 0.3304]])

In [5]:
tensor_AB = torch.matmul(tensor_A, tensor_B.T)
tensor_AB

tensor([[1.4856],
        [2.5008],
        [1.5445],
        [2.3210],
        [1.4833],
        [2.3743],
        [1.7489]])

In [12]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(size=(7,7))

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(size=(1,7))

tensor_AB_rseed = torch.matmul(tensor_A, tensor_B.T)
tensor_AB_rseed, tensor_AB_rseed.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [ ]:
torch.cuda.manual_seed(1234)

In [5]:
import torch
import random

torch.manual_seed(1234)
tensor_C = torch.rand(size=(2,3))

torch.manual_seed(1234)
tensor_D = torch.rand(size=(2,3))

tensor_C_GPU = tensor_C.to(device = "cuda")
tensor_D_GPU = tensor_D.to(device = "cuda")

tensor_C_GPU, tensor_D_GPU

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [6]:
tensor_CD_GPU = torch.matmul(tensor_C_GPU, tensor_D_GPU.T)
tensor_CD_GPU

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [7]:
tensor_CD_GPU.max(), tensor_CD_GPU.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [12]:
tensor_CD_GPU_argmax = tensor_CD_GPU.argmax()
tensor_CD_GPU_argmin = tensor_CD_GPU.argmin()
tensor_CD_GPU_argmax, tensor_CD_GPU_argmin

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [16]:
torch.manual_seed(7)
tensor_E = torch.rand(size=(1,1,1,10))
tensor_E_squeeze = tensor_E.squeeze()
print(f"First tensor:\n{tensor_E}\n")
print(f"First tensor shape:\n{tensor_E.shape}\n")
print(f"Squeezed tensor:\n{tensor_E_squeeze}\n")
print(f"Squeezed tensor shape:\n{tensor_E_squeeze.shape}")

First tensor:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

First tensor shape:
torch.Size([1, 1, 1, 10])

Squeezed tensor:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

Squeezed tensor shape:
torch.Size([10])
